name: Update Coverage

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main]
  schedule:
    # Run daily at 6 AM UTC to catch any drift
    - cron: '0 6 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update-coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install system dependencies for gnubg
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            autoconf \
            automake \
            libtool \
            pkg-config \
            libglib2.0-dev \
            libreadline-dev \
            libsqlite3-dev \
            bison \
            flex

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Update coverage in README
        run: npm run update-coverage

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Coverage badges updated"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No coverage changes detected"
          fi

      - name: Commit changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "chore: update coverage badges [skip ci]" || exit 0
          git push || echo "No changes to push"

      - name: Comment on PR
        if: github.event_name == 'pull_request' && steps.verify-changed-files.outputs.changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const readme = fs.readFileSync('README.md', 'utf8');
            const coverageMatch = readme.match(/<!-- COVERAGE-START -->([\s\S]*?)<!-- COVERAGE-END -->/);

            if (coverageMatch) {
              const coverageBadges = coverageMatch[1].trim();
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## 📊 Coverage Update\n\n${coverageBadges}\n\n*Coverage badges updated automatically.*`
              });
            }
